<style>
.this_page{
    text-align: justify;
    text-justify: inter-word;
}

</style>

<div  class="col-md-6 this_page">
          <h3 class="adlinks">Dear Friends and Colleagues,</h3>
            <p>My name is <strong>Wayne Blanchard</strong> and I am a <u>veteran NJ State Trooper</u>. I started my law enforcement career in 2001 as a Middlesex County Corrections Officer. I know what it means to rely on our fellow brothers and sister officers to watch each other&rsquo;s back while being outnumbered 50 to 1, without a gun, behind the walls of a correctional facility. The bounds and camaraderie to one another can&rsquo;t be described, but is something I treasure dearly. To try and sum it up in one word would be <strong>&ldquo;family&rdquo;</strong> or <strong>&ldquo;Brotherhood.&rdquo; </strong>On September 28, 2008, I suffered the tragic loss of my friend and fellow <strong>Elizabeth Police Officer Jason Samaritano</strong> in an off duty automobile accident. In an effort to provide comfort and relief to his family, a group of Jason&rsquo;s friends organized a benefit event for the Samaritano family in December. While organizing that benefit, I contacted <strong>the New Jersey Law Enforcement Police Officer&rsquo;s Brotherhood (POB)</strong> and met with representatives from that organization at the annual <u><strong><a class="adlinks" href="/nav-to-page.php?subNav=3&outputMess=Blue Mass&content=bluemass.php">Blue Mass in Newark</a></strong></u>. Without hesitation, the POB responded by attending the benefit event and providing a very generous donation to Jason&rsquo;s family, <strong>even though Jason or <u>I were not members</u> of the POB.</strong><br />
          <br />Due to their unselfish and generous actions, by providing monetary relief for Jason&rsquo;s family, without asking for anything in return, I immediately became a member of the BROTHERHOOD. After becoming a member, I was made aware of some other unfortunate situations. First, in December of 2008, the untimely demise of <strong>Middlesex County Corrections Lieutenant Alan Deverin</strong> from a brain aneurysm and second, <strong>New Jersey State Police Sergeant Jim Meyers</strong> whose son Ryan is suffering from a rare form of cancer. As a member, I brought these concerns to the Executive Board of the POB and again received another generous response to these unfortunate situations. Each family was provided with monetary relief on behalf of the BROTHERHOOD. <u>I was so touched by their support; I asked to get involved to help grow the brotherhood in order for us to help more officers and their families during their time of need or crises in the future. </u>I am proud to say that I have gotten hundreds of law enforcement officers and civilians to join this worthy organization and its cause to financially support law enforcement officer and their families during their time of need.&nbsp; Due to my efforts the Executive Board has appointed me to the position of <strong>Director of Public Relations</strong> and the POB has given thousands of dollars to officers and their families through various fundraising programs! </p>
          <p>Please go to the <strong>&ldquo;<a class="adlinks" href="/nav-to-page.php?subNav=2&outputMess=Making A Difference&content=making-a-difference.php">we are making a difference</a>&rdquo;</strong> tab to see our generosity, efforts and financial support to the law enforcement community regardless of their union affiliation. The POB&rsquo;s position is to unit all law enforcement to be a part of our family called <strong>&ldquo;the Brotherhood&rdquo;</strong>. As brother and sister law enforcement officers, we Blue Bloods together, can make the thin blue line stronger!</p>
        </div>

<div  class="col-md-6 this_page">
          <img src="<?= base_url() ?>public/images/blanchard_troopers.jpg" class="img-responsive" width="500" height="300" alt="Wayne Blanchard with state troopers" />
          <p>Therefore, I am urging all Law Enforcement Officers to take a minute to join this great organization by going to the <strong>&ldquo;<a class="adlinks" href="/members/membership.php" >become a member</a>&rdquo;</strong> tab to register with us, and if you&rsquo;re a civilian, become an Associate Member to help us form an alliance in support of the law enforcement community. We would appreciate your help by getting your friends, family and neighbors to &ldquo;<strong><a class="adlinks" href="/members/donor-page.php" >make a donation</a>&rdquo;</strong> or businesses can <strong>&ldquo;<a class="adlinks" href="/members/ad-page.php" >advertise your business</a>&rdquo;</strong> in our Police Officers Yearbook.</p>
            <p>The organization's main goals is to bring back the true meaning of <strong>brotherhood </strong>among law enforcements officers in our great state, assist law enforcement officers and their families during their time of need or crisis, whatever that need may be, and finally to have a voice in support of law enforcement causes within the legislative houses in Trenton and Washington DC. The POB is <strong><u>not a labor union</u></strong> or affiliated with any other police labor union, bargaining agent or lobbying group, nor does it compete with the state PBA, FOP or STFA. <strong>The POB exists solely for the benefit of its members and the law enforcement community as a whole!</strong> Our board is comprised of active and retired law enforcement officers throughout the state. Due to the POB&rsquo;s unselfish generosity through our fundraising programs and events the recognition has been overwhelming and we have been asked to expand our organization <strong>nationally throughout the United States</strong>. Officers from other states have contacted us to become a part of the BROTHERHOOD on a national level and we are in the process of making that happen. With your help we will make the <u>thin blue line</u> stronger. Therefore, help us help you by spreading the word about this great organization and join our law enforcement family called &ldquo;The <strong>BROTHERHOOD&rdquo;</strong> today.<br />
          <br />Benevolently yours,
          <br />Wayne Blanchard,
          <br />Director &amp; New Jersey State Trooper </p>
          <img src="<?= base_url(); ?>public/images/blanchard_podium.jpg" class="img-responsive" width="200" height="240" /><br />
        </div>
