	<div class="div-menu-inner-2Col">
		<p>On Friday October 24, 2003 at the Essex County PBA Conference Dinner, Chairman William Brennan called up, President Michael Sica, Sr. of the Police Brotherhood to presented a check to <span style="text-decoration: underline;">Bloomfield PBA Local #32</span> President Michael Ruggiero in the amount of <strong>$1,000.00</strong> for their legal defense fund, to help the 4 officers who were indicted while responding to a medical assistance call of an individual who was having a violent seizure.</p>
		<p>At said dinner/dance President Sica also praised Bloomfield Police Chief Jack McNiff for his decision not to suspend the 4 officers who were indicted despite outside political influences and pressure. President Sica commended Chief McNiff and stated that more police chiefs should have your veracity and stand behind the men and women in uniform who serve and protect the citizens of the state of New Jersey.</p>
		<p>Too many times when officers are charged their department usually suspends them without pay in order to show the public that they are taking action regardless of knowing all of the facts or conducting a thorough investigation. What ever happened to <span style="color: #3366ff;">“innocent until proven guilty”</span>? The emotional &amp; financial strain that is placed on an officer &amp; their family when suspended without pay has been known to be deadly at times. Therefore, President Sica commended Chief McNiff for administratively resigning the officers to modified non firearms desk duty with pay until the case could be properly investigated and adjudicated. More Police Chiefs, Directors and Law Enforcement Agencies or Departments throughout our Nation should follow his leadership and judgment.</p>
		<p> </p>
		<p><span style="color: #0000ff;"> We are proud to announce that after a thorough investigation was conducted and all of the facts presented, Judge Vichness of the Superior Court in Essex County dismissed th<span style="color: #3366ff;">e cases against these officers</span></span><strong><span style="color: #3366ff;"> March 5, 2004</span>.</strong> The Police Brotherhood is just trying to do its part to educate the public to ensure that justice prevails instead of politics as usual. While politicians cower down to special interest groups and the media helps flame the fires of resentment toward our law enforcement profession without knowing all of the facts just to break the story first and garner more ratings, sensationalism and spewing more misinformation then reporting factual news. This does a disservice to the men and women in blue and to you the public! <span style="color: red;">We’re Making a Difference because we are compelled to right these wrongs in order for everyone to be treated fairly and receive their due process!</span></p>
	</div>
	<div class="div-menu-inner-2Col">
		<p><img class="pics-type1" src="<?= base_url(); ?>public/images/gallery/donation1.jpg" alt="" width="302" height="250" /></p>
		<p><img class="pics-type1" src="<?= base_url(); ?>public/images/gallery/donation2.jpg" alt="" width="302" height="250" /></p>
	</div>
